#!/usr/bin/env python3
"""
Reference Verifier Utilities
- Parse references from text
- Fuzzy match titles/authors
- Generate BibTeX entries
- Generate 4-level audit reports
"""

import re
import json
import unicodedata
from difflib import SequenceMatcher
from typing import Optional


# ── Text normalization and fuzzy matching ──────────────────────────────

def normalize_text(text: str) -> str:
    """Normalize text for comparison: lowercase, strip accents, remove punctuation."""
    text = text.lower().strip()
    text = unicodedata.normalize('NFKD', text)
    text = ''.join(c for c in text if not unicodedata.combining(c))
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text


def fuzzy_match(s1: str, s2: str) -> float:
    """Return similarity ratio (0-1) between two strings."""
    return SequenceMatcher(None, normalize_text(s1), normalize_text(s2)).ratio()


def title_match(ref_title: str, db_title: str, threshold: float = 0.85) -> bool:
    """Check if two titles match above threshold."""
    return fuzzy_match(ref_title, db_title) >= threshold


def first_author_match(ref_authors: str, db_authors: str) -> bool:
    """Check if the first author's last name matches."""
    def extract_first_last(authors_str):
        authors_str = authors_str.strip()
        first_author = authors_str.split(',')[0].split(' and ')[0].strip()
        parts = first_author.split()
        if parts:
            return normalize_text(parts[0])
        return ""
    
    ref_last = extract_first_last(ref_authors)
    db_last = extract_first_last(db_authors)
    
    if not ref_last or not db_last:
        return False
    return ref_last == db_last or fuzzy_match(ref_last, db_last) > 0.8


# ── Status icons ───────────────────────────────────────────────────────

STATUS_ICONS = {
    # Level 1
    'EXISTS': '✅',
    'NOT_FOUND': '❌',
    # Level 2
    'METADATA_CORRECT': '✅',
    'METADATA_MINOR_ERRORS': '⚠️',
    'METADATA_MAJOR_ERRORS': '❌',
    # Level 3
    'TOPIC_CONFIRMED': '✅',
    'TOPIC_PERIPHERAL': '⚠️',
    'TOPIC_NOT_FOUND': '❌',
    'TOPIC_UNVERIFIABLE': '❓',
    # Level 4
    'CITATION_CORRECT': '✅',
    'CITATION_MISLEADING': '❌',
    'CITATION_EXAGGERATED': '⚠️',
    'CITATION_IMPRECISE': '⚠️',
    'CITATION_UNVERIFIABLE': '❓',
    'CITATION_METHOD_ONLY': 'ℹ️',
}

def icon(status: str) -> str:
    return STATUS_ICONS.get(status, '❓')


# ── BibTeX generation ──────────────────────────────────────────────────

def make_citation_key(authors: str, year: str, existing_keys: set) -> str:
    """Generate a BibTeX citation key like 'Smith2024a'."""
    author_part = authors.strip().split(',')[0].split(' and ')[0].strip().split()
    if author_part:
        last_name = re.sub(r'[^\w]', '', author_part[0])
    else:
        last_name = "Unknown"
    
    base_key = f"{last_name}{year}"
    key = base_key
    suffix_idx = 0
    while key in existing_keys:
        key = f"{base_key}{chr(ord('a') + suffix_idx)}"
        suffix_idx += 1
    existing_keys.add(key)
    return key


def to_bibtex_entry(ref: dict, existing_keys: set) -> str:
    """Convert a reference dict to a BibTeX @article entry."""
    key = make_citation_key(
        ref.get('authors', 'Unknown'),
        ref.get('year', 'XXXX'),
        existing_keys
    )
    
    lines = [f"@article{{{key},"]
    
    field_map = {
        'authors': 'author',
        'title': 'title',
        'journal': 'journal',
        'year': 'year',
        'volume': 'volume',
        'issue': 'number',
        'pages': 'pages',
        'doi': 'doi',
        'pmid': 'pmid',
    }
    
    for ref_key, bib_key in field_map.items():
        value = ref.get(ref_key, '').strip()
        if value:
            value = value.replace('&', r'\&').replace('_', r'\_').replace('%', r'\%')
            lines.append(f"  {bib_key:<10} = {{{value}}},")
    
    lines.append("}")
    return '\n'.join(lines)


def generate_bib_file(references: list[dict]) -> str:
    """Generate complete BibTeX file from verified references."""
    existing_keys = set()
    entries = []
    
    for ref in references:
        if ref.get('level1_status') == 'EXISTS':
            entries.append(to_bibtex_entry(ref, existing_keys))
    
    header = (
        "% BibTeX file generated by Reference Verifier\n"
        f"% Total entries: {len(entries)}\n"
        "% Metadata corrected from PubMed/CrossRef where available\n"
        "%\n\n"
    )
    return header + '\n\n'.join(entries) + '\n'


# ── Audit report generation ───────────────────────────────────────────

def generate_audit_report(references: list[dict]) -> str:
    """Generate a comprehensive 4-level audit report in markdown."""
    total = len(references)
    
    # Level 1 counts
    l1_exists = sum(1 for r in references if r.get('level1_status') == 'EXISTS')
    l1_not_found = sum(1 for r in references if r.get('level1_status') == 'NOT_FOUND')
    
    # Level 2 counts
    l2_correct = sum(1 for r in references if r.get('level2_status') == 'METADATA_CORRECT')
    l2_minor = sum(1 for r in references if r.get('level2_status') == 'METADATA_MINOR_ERRORS')
    l2_major = sum(1 for r in references if r.get('level2_status') == 'METADATA_MAJOR_ERRORS')
    
    # Level 3 counts
    l3_confirmed = sum(1 for r in references if r.get('level3_status') == 'TOPIC_CONFIRMED')
    l3_peripheral = sum(1 for r in references if r.get('level3_status') == 'TOPIC_PERIPHERAL')
    l3_not_found = sum(1 for r in references if r.get('level3_status') == 'TOPIC_NOT_FOUND')
    l3_unverifiable = sum(1 for r in references if r.get('level3_status') == 'TOPIC_UNVERIFIABLE')
    
    # Level 4 counts
    l4_correct = sum(1 for r in references if r.get('level4_status') == 'CITATION_CORRECT')
    l4_misleading = sum(1 for r in references if r.get('level4_status') == 'CITATION_MISLEADING')
    l4_exaggerated = sum(1 for r in references if r.get('level4_status') == 'CITATION_EXAGGERATED')
    l4_imprecise = sum(1 for r in references if r.get('level4_status') == 'CITATION_IMPRECISE')
    l4_unverifiable = sum(1 for r in references if r.get('level4_status') == 'CITATION_UNVERIFIABLE')
    
    lines = []
    
    # ── Executive Summary ──
    lines.append("# Reference Audit Report\n")
    lines.append("## Executive Summary\n")
    lines.append(f"**Total references audited: {total}**\n")
    lines.append("| Level | Status | Count |")
    lines.append("|-------|--------|-------|")
    lines.append(f"| 1. Existence | ✅ Verified | {l1_exists} |")
    lines.append(f"| 1. Existence | ❌ Not Found | {l1_not_found} |")
    lines.append(f"| 2. Metadata | ✅ Correct | {l2_correct} |")
    lines.append(f"| 2. Metadata | ⚠️ Minor Errors | {l2_minor} |")
    lines.append(f"| 2. Metadata | ❌ Major Errors | {l2_major} |")
    lines.append(f"| 3. Topical | ✅ Confirmed | {l3_confirmed} |")
    lines.append(f"| 3. Topical | ⚠️ Peripheral | {l3_peripheral} |")
    lines.append(f"| 3. Topical | ❌ Not Found | {l3_not_found} |")
    lines.append(f"| 3. Topical | ❓ Unverifiable | {l3_unverifiable} |")
    lines.append(f"| 4. Context | ✅ Correct | {l4_correct} |")
    lines.append(f"| 4. Context | ❌ Misleading | {l4_misleading} |")
    lines.append(f"| 4. Context | ⚠️ Exaggerated | {l4_exaggerated} |")
    lines.append(f"| 4. Context | ⚠️ Imprecise | {l4_imprecise} |")
    lines.append(f"| 4. Context | ❓ Unverifiable | {l4_unverifiable} |")
    lines.append("")
    
    # ── Critical Issues ──
    critical = [r for r in references if r.get('level1_status') == 'NOT_FOUND'
                or r.get('level2_status') == 'METADATA_MAJOR_ERRORS'
                or r.get('level3_status') == 'TOPIC_NOT_FOUND'
                or r.get('level4_status') == 'CITATION_MISLEADING'
                or r.get('is_retracted', False)]
    
    if critical:
        lines.append("\n## 🚨 Critical Issues (Action Required)\n")
        for r in critical:
            ref_num = r.get('ref_number', '?')
            title = r.get('title', 'N/A')
            issues = []
            if r.get('level1_status') == 'NOT_FOUND':
                issues.append("Reference not found in any database")
            if r.get('level2_status') == 'METADATA_MAJOR_ERRORS':
                issues.append(f"Major metadata errors: {r.get('metadata_errors', 'see details')}")
            if r.get('level3_status') == 'TOPIC_NOT_FOUND':
                issues.append("Cited paper does not cover the cited topic")
            if r.get('level4_status') == 'CITATION_MISLEADING':
                issues.append(f"Citation is misleading: {r.get('context_notes', 'see details')}")
            if r.get('is_retracted'):
                issues.append("⚠️ THIS PAPER HAS BEEN RETRACTED")
            
            lines.append(f"- **[{ref_num}] {title}**")
            for issue in issues:
                lines.append(f"  - {issue}")
            lines.append("")
    
    # ── Detailed Audit ──
    lines.append("\n## Detailed Audit by Reference\n")
    
    for r in references:
        ref_num = r.get('ref_number', '?')
        authors = r.get('authors', 'N/A')
        year = r.get('year', 'N/A')
        title = r.get('title', 'N/A')
        
        lines.append(f"### Reference [{ref_num}]: {authors} ({year})")
        lines.append(f"**Title**: {title}\n")
        
        # Level 1
        l1 = r.get('level1_status', 'N/A')
        l1_detail = r.get('level1_detail', '')
        lines.append(f"**Level 1 — Existence**: {icon(l1)} {l1}")
        if l1_detail:
            lines.append(f"  {l1_detail}")
        
        # Level 2
        l2 = r.get('level2_status', 'N/A')
        lines.append(f"\n**Level 2 — Metadata**: {icon(l2)} {l2}")
        if r.get('metadata_errors'):
            for field, detail in r['metadata_errors'].items():
                lines.append(f"  - {field}: manuscript has \"{detail['manuscript']}\" → correct: \"{detail['correct']}\"")
        
        # Level 3
        l3 = r.get('level3_status', 'N/A')
        lines.append(f"\n**Level 3 — Topical Relevance**: {icon(l3)} {l3}")
        if r.get('cited_for'):
            lines.append(f"  - Cited for: {r['cited_for']}")
        if r.get('topic_notes'):
            lines.append(f"  - Assessment: {r['topic_notes']}")
        
        # Level 4
        citations = r.get('citation_contexts', [])
        if citations:
            lines.append(f"\n**Level 4 — Contextual Accuracy**:")
            for ctx in citations:
                l4 = ctx.get('status', 'N/A')
                lines.append(f"  - Context: \"{ctx.get('text', 'N/A')}\"")
                lines.append(f"    - Usage type: {ctx.get('usage_type', 'N/A')}")
                lines.append(f"    - Assessment: {icon(l4)} {l4}")
                if ctx.get('notes'):
                    lines.append(f"    - Notes: {ctx['notes']}")
        else:
            l4 = r.get('level4_status', 'N/A')
            lines.append(f"\n**Level 4 — Contextual Accuracy**: {icon(l4)} {l4}")
            if r.get('context_notes'):
                lines.append(f"  - {r['context_notes']}")
        
        lines.append("\n---\n")
    
    # ── Metadata Corrections Table ──
    refs_with_errors = [r for r in references if r.get('metadata_errors')]
    if refs_with_errors:
        lines.append("\n## Metadata Corrections\n")
        lines.append("| Ref # | Field | In Manuscript | Correct Value |")
        lines.append("|-------|-------|---------------|---------------|")
        for r in refs_with_errors:
            ref_num = r.get('ref_number', '?')
            for field, detail in r['metadata_errors'].items():
                lines.append(f"| [{ref_num}] | {field} | {detail['manuscript']} | {detail['correct']} |")
        lines.append("")
    
    # ── Recommendations ──
    lines.append("\n## Recommendations\n")
    
    if l1_not_found > 0:
        lines.append("### References Not Found")
        lines.append("The following references could not be found in PubMed, CrossRef, or Scholar databases. "
                      "They should be verified manually or replaced:\n")
        for r in references:
            if r.get('level1_status') == 'NOT_FOUND':
                lines.append(f"- [{r.get('ref_number', '?')}] \"{r.get('title', 'N/A')}\"")
        lines.append("")
    
    if l4_misleading + l4_exaggerated > 0:
        lines.append("### Citation Accuracy Issues")
        lines.append("The following citations may need revision to accurately reflect their sources:\n")
        for r in references:
            contexts = r.get('citation_contexts', [])
            for ctx in contexts:
                if ctx.get('status') in ('CITATION_MISLEADING', 'CITATION_EXAGGERATED'):
                    lines.append(f"- [{r.get('ref_number', '?')}]: {ctx.get('notes', 'See details above')}")
        lines.append("")
    
    return '\n'.join(lines)


# ── Self-test ──────────────────────────────────────────────────────────

if __name__ == "__main__":
    test_refs = [
        {
            "ref_number": 1,
            "title": "Deep learning in medical imaging: a comprehensive review",
            "authors": "Smith, John and Doe, Jane",
            "year": "2024",
            "journal": "Nature Medicine",
            "volume": "30",
            "pages": "100-115",
            "doi": "10.1038/s41591-024-00001-1",
            "pmid": "38000001",
            "level1_status": "EXISTS",
            "level1_detail": "Found in PubMed (PMID: 38000001)",
            "level2_status": "METADATA_MINOR_ERRORS",
            "metadata_errors": {
                "pages": {"manuscript": "100-110", "correct": "100-115"}
            },
            "level3_status": "TOPIC_CONFIRMED",
            "cited_for": "AI applications in radiology",
            "topic_notes": "Central topic of the review",
            "citation_contexts": [
                {
                    "text": "AI has shown promise in radiology [1]",
                    "usage_type": "SUPPORTS",
                    "status": "CITATION_CORRECT",
                    "notes": None
                }
            ]
        },
        {
            "ref_number": 2,
            "title": "A completely fabricated study on unicorn pathology",
            "authors": "Fakeson, Bob",
            "year": "2024",
            "journal": "Journal of Nonexistence",
            "volume": "1",
            "pages": "1-5",
            "level1_status": "NOT_FOUND",
            "level1_detail": "Not found in PubMed, CrossRef, or Scholar Gateway",
            "level2_status": "N/A",
            "level3_status": "N/A",
            "level4_status": "N/A",
            "citation_contexts": []
        },
    ]
    
    print("=== BibTeX Output ===")
    print(generate_bib_file(test_refs))
    print("\n=== Audit Report ===")
    print(generate_audit_report(test_refs))
